### ISSUE TITLE
Odd sized images do not work

### ISSUE THREAD

**Issue by brlnoble** [brlnoble/Image_Encoder-Decoder#1]
Images where the X and/or Y pixel count is not an even number do not work.

```
Traceback (most recent call last):
  File "c:\Users\brlno\Documents\6th Year\4TN4\Project1.py", line 260, in <module>
    blue_img_comp = Down_Sample(blue_img,4) #compress U by 4
  File "c:\Users\brlno\Documents\6th Year\4TN4\Project1.py", line 66, in Down_Sample
    img_comp[x//factor,y//factor] = np.mean(img[x:x+factor,y:y+factor])
IndexError: index 118 is out of bounds for axis 1 with size 118
```

Image is as below. 475x318 pixels.
![waterfall](https://user-images.githubusercontent.com/51976754/218002167-416365e0-0bfd-4801-89c4-90f6bf955e4d.png)

- [x] Fix downscaling function
- [x] Fix upscaling function

**Comment by brlnoble** [comment]
Fixed with https://github.com/brlnoble/Image_Encoder-Decoder/commit/1fcd24e7873f7da1154258107289cc713bf0ac4f

Program now checks for odd sized images and adjusts accordingly.
